name: NyaaBank
main: cat.nyaa.nyaabank.NyaaBank
description: "Simplified realistic banking system for players to setup their private bank. Designed for NyaaCat server."
version: ${version}
depend: [Vault, NyaaCore]
softdepend: []
authors: [RecursiveG]
website: "https://github.com/NyaaCat/NyaaBank"
api-version: 1.13

commands:
  nyaabank:
    description: The command for NyaaBank
    aliases: nb
    permission: nb.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  nb.command:
    description: Run bank command
    default: true
  nb.user:
    description: Default permissions for normal player
    default: true
    children:
      nb.deposit: true
      nb.withdraw: true
      nb.loan: true
      nb.repay: true
      nb.list_my: true

  nb.banker:
    description: Default permissions for bankers
    default: true
    children:
      nb.bank_list: true
      nb.bank_info: true
      nb.bank_interest: true
      nb.bank_customers: true
      nb.bank_vault: true

      nb.sign_create: true
      nb.sign_break: true

  nb.admin:
    description: Permissions for the god
    default: op
    children:
      nb.bank_list_admin: true
      nb.bank_info_admin: true
      nb.bank_interest_admin: true
      nb.bank_customers_admin: true
      nb.bank_vault_admin: true

      nb.list_my_admin: true
      nb.sign_create_admin: true
      nb.sign_break_admin: true

      nb.create_bank: true
      nb.force_bankrupt: true
      nb.top: true
      nb.reload: true

  nb.tansaction_cmds:
    description: Allow players to interact with bank from command
    default: op
    children:
      nb.deposite_cmd: true
      nb.withdraw_cmd: true
      nb.loan_cmd: true
      nb.repay_cmd: true

  nb.debug:
    description: Access to all dev/debug functions
    default: op # change to false when releasing
